name: clean_dart_flutter_command
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_command: ^2.0.1
  functional_listener: ^2.0.2
  uno: ^1.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mocktail: ^0.2.0
  value_listenable_test: ^0.0.1

flutter:
  uses-material-design: true
  # assets:
    # Add assets from the images directory to the application.
    # - assets/images/
